import torch

GPU_ID = torch.device("cuda:3")
MAX_SEQ_LENGTH = 512
BATCH_SIZE = 16
EPOCHS = 16
CROSS_ENTROPY_IGNORE_INDEX = -100
MODEL_NAME = "CAMeL-Lab/bert-base-arabic-camelbert-ca"
NER_EMBEDDING_SIZE = 768
NER_EMBEDDING_MAX_NORM = 1
NER_N_LABELS = 2
NER_EMBEDDING_PAD = NER_N_LABELS

QUESTION_EMBEDDING_SIZE = 768
QUESTION_EMBEDDING_MAX_NORM = 1
